### ISSUE TITLE
Backend overview

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [cssoftwareengineering2animap/rfcs#5]
![image](https://user-images.githubusercontent.com/17282221/91672041-17cd1680-eb02-11ea-93e1-326bcf0fc9c8.png)

**Comment by PoorlyDefinedBehaviour** [comment]
@Gabrieroo Opiniões?

**Comment by gui-fkb** [comment]
Criar uma entidade que representa um "Card" para os anfitriões??

**Comment by gui-fkb** [comment]
Será que precisa mesmo que o pet tenha uma carteira de vacinação? Muita burocracia pra fazer um cadastro, acho que seria mais dinâmico do ponto de vista do usuário se a gente removesse isso

**Comment by PoorlyDefinedBehaviour** [comment]
> Será que precisa mesmo que o pet tenha uma carteira de vacinação? Muita burocracia pra fazer um cadastro, acho que seria mais dinâmico do ponto de vista do usuário se a gente removesse isso

Por mim não tem problema

@Gabrieroo ?

**Comment by PoorlyDefinedBehaviour** [comment]
> Criar uma entidade que representa um "Card" para os anfitriões??

Já sabemos as informações que vão ter no card na hora de mostrar? Dependendo delas não precisa

**Comment by Gabrieroo** [comment]
Por mim sem ´problemas, era mais pra gente ter oque fazer no trabalho, mas como estamos botando mais coisas, nao precisa.

**Comment by PoorlyDefinedBehaviour** [comment]
> Por mim sem ´problemas, era mais pra gente ter oque fazer no trabalho, mas como estamos botando mais coisas, nao precisa.

Ok, vamos remover então.

**Comment by PoorlyDefinedBehaviour** [comment]
Outdated
