### ISSUE TITLE
Upload de imagens

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [cssoftwareengineering2animap/rfcs#7]
Upload de imagens

Como um usuário, 
quero ser capaz de adicionar fotos minhas e fotos dos meus pets.

**Comment by PoorlyDefinedBehaviour** [comment]
Não sei onde deixar as imagens, deixar no disco seria o suficiente por não ser um projeto sério.
Mas acho melhor colocar na amazon ou digitalocean se tiverem um free tier.

**Comment by Gabrieroo** [comment]
No caso, protótipo?

**Comment by PoorlyDefinedBehaviour** [comment]
> No caso, protótipo?

pog, respondendo as issues

não entendi a pergunta

**Comment by Gabrieroo** [comment]
Fotos dos protótipos, e dos modelos do arquiteture.

**Comment by PoorlyDefinedBehaviour** [comment]
> Fotos dos protótipos, e dos modelos do arquiteture.

Não, estou falando das fotos do usuário e dos pets.

**Comment by PoorlyDefinedBehaviour** [comment]
> Não sei onde deixar as imagens, deixar no disco seria o suficiente por não ser um projeto sério.
> Mas acho melhor colocar na amazon ou digitalocean se tiverem um free tier.

Pensando bem, salvar no disco é uma péssima ideia, por fazer ser "impossível" rodar o servidor em mais de uma máquina.

**Comment by Gabrieroo** [comment]
https://aws.amazon.com/pt/free/storage/
Podemos ver pra usar da amazon.

**Comment by PoorlyDefinedBehaviour** [comment]
> https://aws.amazon.com/pt/free/storage/

Tava olhando essa agora, acho que serve pro nosso caso;

Talvez integrar https://aws.amazon.com/cloudfront/?did=ft_card&trk=ft_card se sobrar tempo

**Comment by PoorlyDefinedBehaviour** [comment]
O free tier da amazon é legal mas precisa botar o cartão e não da pra settar um hard limit no gasto e eu não to afim de ir a falência ainda.

Vou ver se da pra usar o free tier da google cloud. Se não der, provavelmente vamos salvar os arquivos no disco mesmo.
